version: '2'
services:
    prototype-app:
        image: prototype
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prototype-postgresql:5432/prototype
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prototype-postgresql:
        extends:
            file: postgresql.yml
            service: prototype-postgresql
